services:
  front:
    container_name: foodgram-front
    build: frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - frontend_static:/frontend_static

  back:
    container_name: foodgram-back
    build: backend
    env_file: .env
    volumes:
      - django_static:/app/static_backend
      - media:/app/media
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: foodgram-db
    image: postgres:15
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "foodgram" ]
      interval: 5s

  nginx:
    container_name: foodgram-proxy
    build: infra
    ports:
      - '80:80'
    volumes:
      - frontend_static:/static_frontend
      - django_static:/static_backend
      - media:/media
      - ./docs/:/usr/share/nginx/html/api/docs
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - back
      - front

networks:
  default:
    name: foodgram

volumes:
  pg_data:
  django_static:
  media:
  frontend_static:
